# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('secret_code', models.CharField(max_length=50)),
                ('valid_till', models.DateTimeField()),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='orders.OrderItem')),
            ],
        ),
    ]
