# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20170620_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(error_messages={'required': 'Please enter this field'}, max_length=200),
        ),
    ]
